### ISSUE TITLE
NewTestNewOrder returns error code=-1102, msg=Mandatory parameter 'signature' was not sent

### ISSUE THREAD

**Issue by michelemendel** [binance/binance-connector-go#24]
This endpoint is "/api/v3/order/test", so I don't think there should be a signature.

Full error response:
<APIError> code=-1102, msg=Mandatory parameter 'signature' was not sent, was empty/null, or malformed

**Comment by naughtybabyfirst** [comment]
You need to refer to the official documentation to see how to generate a signature and how to use it.

**Comment by alplabin** [comment]
Since the [endpoint](https://developers.binance.com/docs/binance-spot-api-docs/rest-api#test-new-order-trade) security type is [`TRADE`](https://developers.binance.com/docs/binance-spot-api-docs/rest-api#order-rate-limits), a signature is required.

If you had like to test the function and learn how to add a signature, I recommend checking out the following example file: https://github.com/binance/binance-connector-go/blob/main/examples/account/TestNewOrder/TestNewOrder.go
